// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsconfig = {
  aws_project_region: 'us-east-2',
  aws_cognito_identity_pool_id:
    'us-east-2:8c1fe34b-e786-4999-b6b8-02b7ce6ffbdf',
  aws_cognito_region: 'us-east-2',
  aws_user_pools_id: 'us-east-2_9AlobejmS',
  aws_user_pools_web_client_id: '2bmf1sp9pf622o5r8egl23qgki',
  oauth: {},
  aws_appsync_graphqlEndpoint:
    'https://46yagyum2nabbnl4qfbvw7qulm.appsync-api.us-east-2.amazonaws.com/graphql',
  aws_appsync_region: 'us-east-2',
  aws_appsync_authenticationType: 'AMAZON_COGNITO_USER_POOLS'
};

export default awsconfig;
